### ISSUE TITLE
Connecting to a boiler

### ISSUE THREAD

**Issue by bbrdaric** [TLS1000/EQ-3max-simple-boiler-control#1]
Hello!

Great project! I am considering to buy a EQ-3 system so I noticed the only thing missing is boiler control.

I am interested in how did you connect this to your boiler? Currently I have Vaillant boiler connected to an old analog VRT-30 thermostat (three wires).

btw. I found that EQ-3 released standalone boiler controller but I can't find it anywhere to buy http://www.eq-3.de/Downloads/eq3/downloads_produktkatalog/max/bda/en/BC-TS-Sw2-WM_UM_E_eQ-3_160420.pdf

**Comment by TLS1000** [comment]
Hi, I have an old boiler that works with a seperate 'burner', I can control it via power on/off... Upon power ON it will continue to burn untill the boiler thermostat interrupts the power to the boiler. So basically contact from the arduino and the thermostat in series provide burner ON/OFF control.
